### ISSUE TITLE
DeleteEnumVariants transform

### ISSUE THREAD

**Issue by i509VCB** [embassy-rs/chiptool#56]
The MSPM0 SVDs unfortunately contain enums with variants that exist on some parts, but are then not valid on other parts. I would like to delete these enum variants in a transform for some parts.

An example:

```yaml
enum/SYSCTL_SYSOSCCFG_FREQ:
  bit_size: 2
  variants:
  - name: SYSOSCBASE
    value: 0
  - name: SYSOSC4M
    value: 1
  - name: SYSOSCUSER
    value: 2
  # This variant does not actually exist on the MSPM0C110x, but does exist on others
  - name: SYSOSCTURBO
    value: 3
```

I would think the transform to delete variants would be similar in style to `!DeleteFields` transform, kind of like this:

```yaml
- !DeleteEnumVariants
  enums: SYSCTL_SYSOSCCFG_FREQ
  from: SYSOSCTURBO
```
